Algoritmo "Exibir Mensagem"
// Disciplina   : [Lógica da programação e javascript]
// Professor   : Jailson
// Descrição   : Exibir uma mensagem
// Autor(a)    : Thiago
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Jailson - Osasco")
Escreval("Equipe 04")
Escreval("Thiago")


Fimalgoritmo