Algoritmo "Laco Repeticao Enquanto"
//
//
// Descrição   : Laço de repetição com enquanto
// Autor(a)    : Luis Gabriel da Silva
// Professor   : Jailson Santos
// Data atual  : 01/09/2021
Var
// Seção de Declarações das variáveis
contador:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
enquanto contador<10 faca
Escreval("Repetir")
contador<-contador+1
fimenquanto

Fimalgoritmo